# site runs locally at localhost:4000 when you run `jekyll serve --watch`
port:  4000

# ensure UTF-8 character encoding. Be sure to add <meta charset="utf-8"> as well!
encoding: utf-8

# include Pygments for syntax highlighting
pygments: true

